### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pikopie** [IanMooreIsMe/bifrost#1]
How do I install the bot?  Thx

**Comment by yttrian** [comment]
Currently it's not the most ideal method, but it works. I do have to also make some changes at some point to cache the webhook clients to better respect rate limits.

1. Download the latest jar from [releases](https://github.com/IanMooreIsMe/bifrost/releases)
2. Be sure to create a bot in the [Discord Developer portal](https://discordapp.com/developers/applications/) and invite it to your servers and give it Manage Webhooks permission.
3. Set up an environmental variable (look it up if unsure how to) named DISCORD_TOKEN with the bots token. Ideally, I'll add support for a config file at some point. 
4. Run the jar and then ask the bot "bf->setup" to learn how to get started.
